### PR TITLE
Bump version to 0.50.26

### PR DESCRIPTION
**Pull request by AlexVialaBellander**
This isnt working, the build fails with the new version

```
docker build --build-arg METABASE_VERSION=v0.50.26 -t metabase:v0.50.26-databricks -f Dockerfile .
```

```
37.03 Build driver :relferreira_brigad_databricks (edition = :oss, options = {:project-dir "/build/driver", :target-dir "/build/driver/target"})
37.03   Clean
37.03     Delete /build/driver/target/jar if exists
37.03       Don't need to delete /build/driver/target/jar, file does not exist.
37.03     Delete /build/driver/target/relferreira_brigad_databricks.metabase-driver.jar if exists
37.03       Don't need to delete /build/driver/target/relferreira_brigad_databricks.metabase-driver.jar, file does not exist.
37.03   Copy :relferreira_brigad_databricks source files
37.04     Copying files in ["/build/driver/src" "/build/driver/resources"]
37.04     Copying files from /build/driver/src to /build/driver/target/jar
37.04     Copying files from /build/driver/resources to /build/driver/target/jar
37.04     Copied files in 2 directories in 12 ms.
37.04   Compile clojure source files
37.05     Compiling Clojure source files in ["/build/driver/src" "/build/driver/resources"] to /build/driver/target/jar
37.05     Create directory /build/driver/target/jar if it does not exist
37.05       /build/driver/target/jar already exists.
37.05     Compiling namespaces [metabase.driver.connection metabase.driver.FixedSparkDriver metabase.driver.hive-like metabase.driver.sparksql-databricks-v2]
44.06 2024-09-24 13:34:54,967 INFO metabase.util :: Maximum memory available to JVM: 1.9 GB
51.22 2024-09-24 13:35:02,130 INFO util.encryption :: Saved credentials encryption is DISABLED for this Metabase instance. 🔓
51.22  For more information, see https://metabase.com/docs/latest/operations-guide/encrypting-database-details-at-rest.html
53.87 2024-09-24 13:35:04,783 WARN db.env :: WARNING: Using Metabase with an H2 application database is not recommended for production deployments. For production deployments, we highly recommend using Postgres, MySQL, or MariaDB instead. If you decide to continue to use H2, please be sure to back up the database file regularly. For more information, see https://metabase.com/docs/latest/operations-guide/migrating-from-h2.html
54.10 Reflection warning, clojurewerkz/quartzite/triggers.clj:85:6 - call to method forJob on org.quartz.TriggerBuilder can't be resolved (argument types: unknown).
54.13 Reflection warning, clojurewerkz/quartzite/scheduler.clj:254:3 - call to method checkExists on org.quartz.Scheduler can't be resolved (argument types: unknown).
58.22 2024-09-24 13:35:09,139 INFO driver.impl :: Registered abstract driver :metabase.driver.sql-jdbc.execute.legacy-impl/use-legacy-classes-for-read-and-set  🚚
61.64 2024-09-24 13:35:12,553 INFO driver.impl :: Registered abstract driver :sql  🚚
67.56 2024-09-24 13:35:18,479 INFO driver.impl :: Registered abstract driver :sql-jdbc (parents: [:sql]) 🚚
67.62 2024-09-24 13:35:18,534 INFO metabase.util :: Load driver :sql-jdbc took 526.2 ms
67.62 2024-09-24 13:35:18,535 INFO driver.impl :: Registered abstract driver :hive-like (parents: [:sql-jdbc :metabase.driver.sql-jdbc.execute.legacy-impl/use-legacy-classes-for-read-and-set]) 🚚
67.78 2024-09-24 13:35:18,697 INFO driver.impl :: Registered driver :sparksql-databricks-v2 (parents: [:hive-like]) 🚚
67.84     Compiled 4 namespace(s) in 30797 ms.
67.84   Write :relferreira_brigad_databricks :oss uberjar -> /build/driver/target/relferreira_brigad_databricks.metabase-driver.jar
67.84     Determine which dependencies to include
72.95 Downloading: org/clojure/core.logic/1.0.0/core.logic-1.0.0.pom from central
73.06 Downloading: org/clojure/core.logic/1.0.0/core.logic-1.0.0.jar from central
73.09       INCLUDE com.databricks/databricks-jdbc
73.09       SKIP    org.clojure/clojure (provided by metabase-core)
73.09       SKIP    org.clojure/core.logic (provided by metabase-core)
73.09       SKIP    org.clojure/core.specs.alpha (provided by metabase-core)
73.09       SKIP    org.clojure/spec.alpha (provided by metabase-core)
73.23 Building uber jar: /build/driver/target/relferreira_brigad_databricks.metabase-driver.jar
75.67     Created uberjar in 7832 ms.
75.68   Built :relferreira_brigad_databricks driver in 38652 ms.
75.68   Verify :relferreira_brigad_databricks driver
75.68     Check /build/driver/target/relferreira_brigad_databricks.metabase-driver.jar contains init class file metabase/driver/relferreira_brigad_databricks__init.class
75.71 Step failed: Driver verification failed: init class file metabase/driver/relferreira_brigad_databricks__init.class not found
75.75 {:via
75.75  [{:type clojure.lang.ExceptionInfo,
75.75    :message
75.75    "Driver verification failed: init class file metabase/driver/relferreira_brigad_databricks__init.class not found",
75.75    :data {},
75.75    :at [build_drivers.verify$verify_has_init_class$fn__8000 invoke "verify.clj" 32]}],
75.75  :trace
75.75  [[build_drivers.verify$verify_has_init_class$fn__8000 invoke "verify.clj" 32]
75.75   [metabuild_common.steps$do_step invokeStatic "steps.clj" 87]
75.75   [metabuild_common.steps$do_step invoke "steps.clj" 81]
75.75   [build_drivers.verify$verify_has_init_class invokeStatic "verify.clj" 29]
75.75   [build_drivers.verify$verify_has_init_class invoke "verify.clj" 26]
75.75   [build_drivers.verify$verify_driver$fn__8016 invoke "verify.clj" 68]
75.75   [metabuild_common.steps$do_step invokeStatic "steps.clj" 87]
75.75   [metabuild_common.steps$do_step invoke "steps.clj" 81]
75.75   [build_drivers.verify$verify_driver invokeStatic "verify.clj" 66]
75.75   [build_drivers.verify$verify_driver invoke "verify.clj" 62]
75.75   [build_drivers.build_driver$build_driver_BANG_$fn__8032 invoke "build_driver.clj" 39]
75.75   [metabuild_common.steps$do_step invokeStatic "steps.clj" 87]
75.75   [metabuild_common.steps$do_step invoke "steps.clj" 81]
75.75   [build_drivers.build_driver$build_driver_BANG_ invokeStatic "build_driver.clj" 33]
75.75   [build_drivers.build_driver$build_driver_BANG_ invoke "build_driver.clj" 17]
75.75   [build_drivers.build_driver$build_driver_BANG_ invokeStatic "build_driver.clj" 21]
75.75   [build_drivers.build_driver$build_driver_BANG_ invoke "build_driver.clj" 17]
75.75   [clojure.lang.AFn applyToHelper "AFn.java" 154]
75.75   [clojure.lang.AFn applyTo "AFn.java" 144]
75.75   [clojure.lang.Var applyTo "Var.java" 705]
75.75   [clojure.core$apply invokeStatic "core.clj" 667]
75.75   [clojure.core$apply invoke "core.clj" 662]
75.75   [clojure.run.exec$exec invokeStatic "exec.clj" 48]
75.75   [clojure.run.exec$exec doInvoke "exec.clj" 39]
75.75   [clojure.lang.RestFn invoke "RestFn.java" 423]
75.75   [clojure.run.exec$_main$fn__205 invoke "exec.clj" 180]
75.75   [clojure.run.exec$_main invokeStatic "exec.clj" 176]
75.75   [clojure.run.exec$_main doInvoke "exec.clj" 139]
75.75   [clojure.lang.RestFn applyTo "RestFn.java" 137]
75.75   [clojure.lang.Var applyTo "Var.java" 705]
75.75   [clojure.core$apply invokeStatic "core.clj" 667]
75.75   [clojure.main$main_opt invokeStatic "main.clj" 514]
75.75   [clojure.main$main_opt invoke "main.clj" 510]
75.75   [clojure.main$main invokeStatic "main.clj" 664]
75.75   [clojure.main$main doInvoke "main.clj" 616]
75.75   [clojure.lang.RestFn applyTo "RestFn.java" 137]
75.75   [clojure.lang.Var applyTo "Var.java" 705]
75.75   [clojure.main main "main.java" 40]],
75.75  :cause
75.75  "Driver verification failed: init class file metabase/driver/relferreira_brigad_databricks__init.class not found",
75.75  :data {}}
75.75       Step "Check /build/driver/target/relferreira_brigad_databricks.metabase-driver.jar contains init class file metabase/driver/relferreira_brigad_databricks__init.class" failed with error "Driver verification failed: init class file metabase/driver/relferreira_brigad_databricks__init.class not found"
75.75 What would you like to do?
75.75 [T]ry this step again
75.75 [F]ail -- pass the failure of this step to the parent step (which can be retried)
75.75 [S]kip this step
75.75 [R]EPL -- open a REPL so you can debug things
75.75 [Q]uit the build script (or return to the top level if running from the REPL) [T/F/S/R/Q] Step failed:
75.78 {:via [{:type java.lang.NullPointerException, :at [clojure.string$trim invokeStatic "string.clj" 239]}],
75.78  :trace
75.78  [[clojure.string$trim invokeStatic "string.clj" 239]
75.78   [clojure.string$trim invoke "string.clj" 235]
75.78   [metabuild_common.input$read_line_with_prompt invokeStatic "input.clj" 33]
75.78   [metabuild_common.input$read_line_with_prompt doInvoke "input.clj" 19]
75.78   [clojure.lang.RestFn applyTo "RestFn.java" 139]
75.78   [clojure.core$apply invokeStatic "core.clj" 673]
75.78   [clojure.core$apply invoke "core.clj" 662]
75.78   [metabuild_common.input$letter_options_prompt invokeStatic "input.clj" 64]
75.78   [metabuild_common.input$letter_options_prompt doInvoke "input.clj" 52]
75.78   [clojure.lang.RestFn invoke "RestFn.java" 425]
75.78   [metabuild_common.steps$handle_step_failure_interactive invokeStatic "steps.clj" 51]
75.78   [metabuild_common.steps$handle_step_failure_interactive invoke "steps.clj" 47]
75.78   [metabuild_common.steps$do_step invokeStatic "steps.clj" 93]
75.78   [metabuild_common.steps$do_step invoke "steps.clj" 81]
75.78   [build_drivers.verify$verify_has_init_class invokeStatic "verify.clj" 29]
75.78   [build_drivers.verify$verify_has_init_class invoke "verify.clj" 26]
75.78   [build_drivers.verify$verify_driver$fn__8016 invoke "verify.clj" 68]
75.78   [metabuild_common.steps$do_step invokeStatic "steps.clj" 87]
75.78   [metabuild_common.steps$do_step invoke "steps.clj" 81]
75.78   [build_drivers.verify$verify_driver invokeStatic "verify.clj" 66]
75.78   [build_drivers.verify$verify_driver invoke "verify.clj" 62]
75.78   [build_drivers.build_driver$build_driver_BANG_$fn__8032 invoke "build_driver.clj" 39]
75.78   [metabuild_common.steps$do_step invokeStatic "steps.clj" 87]
75.78   [metabuild_common.steps$do_step invoke "steps.clj" 81]
75.78   [build_drivers.build_driver$build_driver_BANG_ invokeStatic "build_driver.clj" 33]
75.78   [build_drivers.build_driver$build_driver_BANG_ invoke "build_driver.clj" 17]
75.78   [build_drivers.build_driver$build_driver_BANG_ invokeStatic "build_driver.clj" 21]
75.78   [build_drivers.build_driver$build_driver_BANG_ invoke "build_driver.clj" 17]
75.78   [clojure.lang.AFn applyToHelper "AFn.java" 154]
75.78   [clojure.lang.AFn applyTo "AFn.java" 144]
75.78   [clojure.lang.Var applyTo "Var.java" 705]
75.78   [clojure.core$apply invokeStatic "core.clj" 667]
75.78   [clojure.core$apply invoke "core.clj" 662]
75.78   [clojure.run.exec$exec invokeStatic "exec.clj" 48]
75.78   [clojure.run.exec$exec doInvoke "exec.clj" 39]
75.78   [clojure.lang.RestFn invoke "RestFn.java" 423]
75.78   [clojure.run.exec$_main$fn__205 invoke "exec.clj" 180]
75.78   [clojure.run.exec$_main invokeStatic "exec.clj" 176]
75.78   [clojure.run.exec$_main doInvoke "exec.clj" 139]
75.78   [clojure.lang.RestFn applyTo "RestFn.java" 137]
75.78   [clojure.lang.Var applyTo "Var.java" 705]
75.78   [clojure.core$apply invokeStatic "core.clj" 667]
75.78   [clojure.main$main_opt invokeStatic "main.clj" 514]
75.78   [clojure.main$main_opt invoke "main.clj" 510]
75.78   [clojure.main$main invokeStatic "main.clj" 664]
75.78   [clojure.main$main doInvoke "main.clj" 616]
75.78   [clojure.lang.RestFn applyTo "RestFn.java" 137]
75.78   [clojure.lang.Var applyTo "Var.java" 705]
75.78   [clojure.main main "main.java" 40]]}
75.78     Step "Verify :relferreira_brigad_databricks driver" failed with error nil
75.78 What would you like to do?
75.78 [T]ry this step again
75.78 [F]ail -- pass the failure of this step to the parent step (which can be retried)
75.78 [S]kip this step
75.78 [R]EPL -- open a REPL so you can debug things
75.78 [Q]uit the build script (or return to the top level if running from the REPL) [T/F/S/R/Q] Step failed:
75.80 {:via [{:type java.lang.NullPointerException, :at [clojure.string$trim invokeStatic "string.clj" 239]}],
75.80  :trace
75.80  [[clojure.string$trim invokeStatic "string.clj" 239]
75.80   [clojure.string$trim invoke "string.clj" 235]
75.80   [metabuild_common.input$read_line_with_prompt invokeStatic "input.clj" 33]
75.80   [metabuild_common.input$read_line_with_prompt doInvoke "input.clj" 19]
75.80   [clojure.lang.RestFn applyTo "RestFn.java" 139]
75.80   [clojure.core$apply invokeStatic "core.clj" 673]
75.80   [clojure.core$apply invoke "core.clj" 662]
75.80   [metabuild_common.input$letter_options_prompt invokeStatic "input.clj" 64]
75.80   [metabuild_common.input$letter_options_prompt doInvoke "input.clj" 52]
75.80   [clojure.lang.RestFn invoke "RestFn.java" 425]
75.80   [metabuild_common.steps$handle_step_failure_interactive invokeStatic "steps.clj" 51]
75.80   [metabuild_common.steps$handle_step_failure_interactive invoke "steps.clj" 47]
75.80   [metabuild_common.steps$do_step invokeStatic "steps.clj" 93]
75.80   [metabuild_common.steps$do_step invoke "steps.clj" 81]
75.80   [build_drivers.verify$verify_driver invokeStatic "verify.clj" 66]
75.80   [build_drivers.verify$verify_driver invoke "verify.clj" 62]
75.80   [build_drivers.build_driver$build_driver_BANG_$fn__8032 invoke "build_driver.clj" 39]
75.80   [metabuild_common.steps$do_step invokeStatic "steps.clj" 87]
75.80   [metabuild_common.steps$do_step invoke "steps.clj" 81]
75.80   [build_drivers.build_driver$build_driver_BANG_ invokeStatic "build_driver.clj" 33]
75.80   [build_drivers.build_driver$build_driver_BANG_ invoke "build_driver.clj" 17]
75.80   [build_drivers.build_driver$build_driver_BANG_ invokeStatic "build_driver.clj" 21]
75.80   [build_drivers.build_driver$build_driver_BANG_ invoke "build_driver.clj" 17]
75.80   [clojure.lang.AFn applyToHelper "AFn.java" 154]
75.80   [clojure.lang.AFn applyTo "AFn.java" 144]
75.80   [clojure.lang.Var applyTo "Var.java" 705]
75.80   [clojure.core$apply invokeStatic "core.clj" 667]
75.80   [clojure.core$apply invoke "core.clj" 662]
75.80   [clojure.run.exec$exec invokeStatic "exec.clj" 48]
75.80   [clojure.run.exec$exec doInvoke "exec.clj" 39]
75.80   [clojure.lang.RestFn invoke "RestFn.java" 423]
75.80   [clojure.run.exec$_main$fn__205 invoke "exec.clj" 180]
75.80   [clojure.run.exec$_main invokeStatic "exec.clj" 176]
75.80   [clojure.run.exec$_main doInvoke "exec.clj" 139]
75.80   [clojure.lang.RestFn applyTo "RestFn.java" 137]
75.80   [clojure.lang.Var applyTo "Var.java" 705]
75.80   [clojure.core$apply invokeStatic "core.clj" 667]
75.80   [clojure.main$main_opt invokeStatic "main.clj" 514]
75.80   [clojure.main$main_opt invoke "main.clj" 510]
75.80   [clojure.main$main invokeStatic "main.clj" 664]
75.80   [clojure.main$main doInvoke "main.clj" 616]
75.80   [clojure.lang.RestFn applyTo "RestFn.java" 137]
75.80   [clojure.lang.Var applyTo "Var.java" 705]
75.80   [clojure.main main "main.java" 40]]}
75.80   Step "Build driver :relferreira_brigad_databricks (edition = :oss, options = {:project-dir \"/build/driver\", :target-dir \"/build/driver/target\"})" failed with error nil
75.80 What would you like to do?
75.80 [T]ry this step again
75.80 [F]ail -- pass the failure of this step to the parent step (which can be retried)
75.80 [S]kip this step
75.80 [R]EPL -- open a REPL so you can debug things
75.80 [Q]uit the build script (or return to the top level if running from the REPL) [T/F/S/R/Q] {:clojure.main/message
75.82  "Execution error (NullPointerException) at metabuild-common.input/read-line-with-prompt (input.clj:33).\nnull\n",
75.82  :clojure.main/triage
75.82  {:clojure.error/class java.lang.NullPointerException,
75.82   :clojure.error/line 33,
75.82   :clojure.error/symbol metabuild-common.input/read-line-with-prompt,
75.82   :clojure.error/source "input.clj",
75.82   :clojure.error/phase :execution},
75.82  :clojure.main/trace
75.82  {:via [{:type java.lang.NullPointerException, :at [clojure.string$trim invokeStatic "string.clj" 239]}],
75.82   :trace
75.82   [[clojure.string$trim invokeStatic "string.clj" 239]
75.82    [clojure.string$trim invoke "string.clj" 235]
75.82    [metabuild_common.input$read_line_with_prompt invokeStatic "input.clj" 33]
75.82    [metabuild_common.input$read_line_with_prompt doInvoke "input.clj" 19]
75.82    [clojure.lang.RestFn applyTo "RestFn.java" 139]
75.82    [clojure.core$apply invokeStatic "core.clj" 673]
75.82    [clojure.core$apply invoke "core.clj" 662]
75.82    [metabuild_common.input$letter_options_prompt invokeStatic "input.clj" 64]
75.82    [metabuild_common.input$letter_options_prompt doInvoke "input.clj" 52]
75.82    [clojure.lang.RestFn invoke "RestFn.java" 425]
75.82    [metabuild_common.steps$handle_step_failure_interactive invokeStatic "steps.clj" 51]
75.82    [metabuild_common.steps$handle_step_failure_interactive invoke "steps.clj" 47]
75.82    [metabuild_common.steps$do_step invokeStatic "steps.clj" 93]
75.82    [metabuild_common.steps$do_step invoke "steps.clj" 81]
75.82    [build_drivers.build_driver$build_driver_BANG_ invokeStatic "build_driver.clj" 33]
75.82    [build_drivers.build_driver$build_driver_BANG_ invoke "build_driver.clj" 17]
75.82    [build_drivers.build_driver$build_driver_BANG_ invokeStatic "build_driver.clj" 21]
75.82    [build_drivers.build_driver$build_driver_BANG_ invoke "build_driver.clj" 17]
75.82    [clojure.lang.AFn applyToHelper "AFn.java" 154]
75.82    [clojure.lang.AFn applyTo "AFn.java" 144]
75.82    [clojure.lang.Var applyTo "Var.java" 705]
75.82    [clojure.core$apply invokeStatic "core.clj" 667]
75.82    [clojure.core$apply invoke "core.clj" 662]
75.82    [clojure.run.exec$exec invokeStatic "exec.clj" 48]
75.82    [clojure.run.exec$exec doInvoke "exec.clj" 39]
75.82    [clojure.lang.RestFn invoke "RestFn.java" 423]
75.82    [clojure.run.exec$_main$fn__205 invoke "exec.clj" 180]
75.82    [clojure.run.exec$_main invokeStatic "exec.clj" 176]
75.82    [clojure.run.exec$_main doInvoke "exec.clj" 139]
75.82    [clojure.lang.RestFn applyTo "RestFn.java" 137]
75.82    [clojure.lang.Var applyTo "Var.java" 705]
75.82    [clojure.core$apply invokeStatic "core.clj" 667]
75.82    [clojure.main$main_opt invokeStatic "main.clj" 514]
75.82    [clojure.main$main_opt invoke "main.clj" 510]
75.82    [clojure.main$main invokeStatic "main.clj" 664]
75.82    [clojure.main$main doInvoke "main.clj" 616]
75.82    [clojure.lang.RestFn applyTo "RestFn.java" 137]
75.82    [clojure.lang.Var applyTo "Var.java" 705]
75.82    [clojure.main main "main.java" 40]]}}
75.82
75.82 Execution error (NullPointerException) at metabuild-common.input/read-line-with-prompt (input.clj:33).
75.82 null
75.82
------

 4 warnings found (use docker --debug to expand):
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 37)
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 45)
 - InvalidDefaultArgInFrom: Default value for ARG metabase/metabase:${METABASE_VERSION} results in empty or invalid base image name (line 49)
 - InvalidBaseImagePlatform: Base image metabase/metabase:v0.50.26 was pulled with platform "linux/amd64", expected "linux/arm64" for current build (line 49)
Dockerfile:38
--------------------
  37 |     FROM stg_base as stg_build
  38 | >>> RUN clojure \
  39 | >>>     -Sdeps "{:aliases {:relferreira_brigad_databricks {:extra-deps {com.metabase/sparksql-databricks {:local/root \"/build/driver\"}}}}}" \
  40 | >>>     -X:build:relferreira_brigad_databricks \
  41 | >>>     build-drivers.build-driver/build-driver! \
  42 | >>>     "{:driver :relferreira_brigad_databricks, :project-dir \"/build/driver\", :target-dir \"/build/driver/target\"}"
  43 |
--------------------
ERROR: failed to solve: process "/bin/sh -c clojure     -Sdeps \"{:aliases {:relferreira_brigad_databricks {:extra-deps {com.metabase/sparksql-databricks {:local/root \\\"/build/driver\\\"}}}}}\"     -X:build:relferreira_brigad_databricks     build-drivers.build-driver/build-driver!     \"{:driver :relferreira_brigad_databricks, :project-dir \\\"/build/driver\\\", :target-dir \\\"/build/driver/target\\\"}\"" did not complete successfully: exit code: 1

View build details: docker-desktop://dashboard/build/desktop-linux/desktop-linux/xam4iu9520x5krohwin5lghud
make: *** [build] Error 1
```

### CODE REVIEW

**Comment by shrodingers** [comment]
No issues on my side, and the error doesnt make sense (Seems weird it tries to load relferreira_brigad_databricks.class)
Gotta check whats different

**Comment by shrodingers** [comment]
Have a PR on my fork that seem to compile fine on latest if you wanna check (https://github.com/Brigad/metabase-sparksql-databricks-driver/pull/8)

**Comment by shrodingers** [comment]
FYI im having the same issue on main here, does not seem related to metabase version but mostly to the aliases on Dockerfile

**Comment by AlexVialaBellander** [comment]
Sus... thanks.. Ill take a look

**Pull request closed without merging**
